sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - '8'

branches:
  only:
    - master
    - travis-ci

before_install:
  - yarn install --no-lockfile
  - yarn global add istanbul coveralls
